travis:
  secure:
    BINSTAR_TOKEN: h/aBrsEcyRVwPs1EDNYDBolI/qdlZ/bpv0uH/hHPlPukDub6x5x/Ixn2Tlc45SRx5Lt8r2CPUPxOWfeihCSjclrYlpd8IWDNr7AlVltqgGVxtjm6l0JvWm8cL7mRNCv1E0J6kDDtSFZwAYQzgxvTdzlGeTOeKifc9T5fUSjcYLZRisvFyz6AcTZtMr2e7ZpRPIknAEvtiPU49qDegs+hcRbb3dQ55IKVIS9i89jNl+cvxB7w1U5o8CJ4GTtM2e3dbmtpyr9d3D31NAZ1CgW6DnpNnJwU/bj68VaZ1bVJFxX5GULbzQtCYkDDUqNQUzJD5IKP+d2gNPaMp9TYAZ0UHu5y2kCvHQ5F9DB7jdXZZPSSvRCYkYpS4TN9T1nRW7m9BcR1f+Yl74yFnBJ8+Gafil1CdgkUve9zLAnjSIPxF0+oh56wu+170hMS7nYgJeLOEN7MN7e6w4OtJ54UAhFNih/fXGmj0YsZev1uZrZQ/36I7tEGP8paP5KFMzorjZayw71H8CXPw5k6MibFWG7fNGAq7OBcyw56A66FcHVixg8ZJ0RWVY5bnhgdLpE8OP8asNOb5+CkX+Qi2olTUybAHncNcz4yji9iJwptw7yIvFPk7+GGctMNk1LzfCpWDTroBU9ugRawRFdjmoc5aUk0cTy/eK7wiidvCaZTYWh3xUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
